
name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04-arm
    steps:
      # Runs a single command using the runners shell
      - name: Install Nix
        run: sh <(curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install) --daemon
      - name: Build
        run: nix build github:nvmd/nixos-raspberrypi#installerImages.rpi5
