name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            
      - name: Set channel to unstable
        run: nix-channel --add https://nixos.org/channels/nixos-unstable nixos

      - name: Update channels
        run: nix-channel --update
        
      - name: Build Pi 5 image
        run: nix build github:nvmd/nixos-raspberrypi#installerImages.rpi5
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: artifact
          path: ./result/*
